version: '3'
services:

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASS}"
      MONGO_INITDB_DATABASE: "${MONGO_DB}"
    volumes:
      - ./data:/var/lib/data
      #- ./init.sh:/docker-entrypoint-initdb.d/init.sh
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongoexpress
    env_file:
      - .env
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USER}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASS}"
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASS}@${MONGO_HOSTNAME}:${MONGO_PORT}/

  fastapi:
    build: .
    container_name: fastapi
    command: bash -c "uvicorn backend.api.main_auth:app --reload --host 0.0.0.0 --port 8000"
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mongo

volumes:
    data:
