version: '3'
services:

  fastapi:
    build: .
    container_name: "fastapi"
    command: bash -c "uvicorn backend.fastapi.main:app --reload --host 0.0.0.0 --port 8000"
    restart: on-failure
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
